### ISSUE TITLE
middleware named arguments

### ISSUE THREAD

**Issue by yanickrochon** [turboMaCk/koa-sslify#1]
Any reason why you use

```
app.use(enforceHttps(true));
```

instead of 

```
app.use(enforeceHttps({
  trustProtoHeader: true
}));
```

Because, if one simply wants to set `temporary` to `true`, he'd have to guess all the previous argument's default values... or just specify them anyhow

```
app.use(enforceHttps(false, false, null, null, null, true));
```

instead of simply

```
app.use(enforceHttps({
  temporary: true
}));
```

IMO, this is quite important to have named arguments. And for you, it will allow adding more options a lot more easily.

**Comment by turboMaCk** [comment]
Thank you for issue.

I agree with this. This is one think I want to change before hitting 1.0.0. The only reason I do not do this before i compatibility with: https://github.com/dotcypress/koa-force-ssl The main idea was to build compatible solution with support for reverse proxy. I'll publish 1.0.0 in about a week. If you want to, You can submit pull request on this.

**Comment by turboMaCk** [comment]
https://github.com/turboMaCk/koa-sslify/pull/3

**Comment by turboMaCk** [comment]
Done in 0.1.0 release: https://github.com/turboMaCk/koa-sslify/releases/tag/v0.1.0
