### ISSUE TITLE
Koa 2

### ISSUE THREAD

**Issue by tonyxiao** [turboMaCk/koa-sslify#11]
Does `koa-sslify` work with koa 2? Would be nice to have some official clarification.

**Comment by turboMaCk** [comment]
@tonyxiao Hi! I did not try it yet. Anyway I want to support Koa 2. Hopefully I'll find some time this weekend to look at this.

Thanks for issue. I'll keep you updated on this.

**Comment by turboMaCk** [comment]
Hello @tonyxiao!
I think #12 do the trick. Anyway I do not know Koa 2 much. Please let me know it there is any complains with that implementation.

**Comment by turboMaCk** [comment]
@tonyxiao Koa2 version published as `koa-sslify@2.0.0` to npm.

**Comment by tonyxiao** [comment]
awesome, looks like it's working! Thanks @turboMaCk
