### ISSUE TITLE
Add options to send Strict-Transport-Security header with redirect

### ISSUE THREAD

**Issue by jkirkwood** [turboMaCk/koa-sslify#16]
It would be nice if there was an option to send the [`Strict-Transport-Security`](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) header, with a `max-age` parameter when redirecting from http to https.

**Comment by turboMaCk** [comment]
Hello @jkirkwood thanks for your request.

I will think about including this but for now I'm not entirely sure if this should or should not be part of this package. Anyway In mean time if you want to do so you can just place any other middleware before koa-sslify to do it.

**Comment by jkirkwood** [comment]
I just realized that this header is only processed by browsers when received over https, and not via a redirect that occurred over http. Consequentially, I don't think this feature belongs in koa-sslify — it really does belong in separate middleware after koa-sslify does its thing.

**Comment by turboMaCk** [comment]
Have a look at https://github.com/koajs/koa-lusca I made few contributions to that package myself. We're using it in production together with koa-sslify.
