### ISSUE TITLE
AssertionError: app.use() requires a generator function

### ISSUE THREAD

**Issue by shapkarin** [turboMaCk/koa-sslify#19]
when I use 

// Force HTTPS on all page 
app.use(enforceHttps())

**Comment by shiwenna** [comment]
+1

**Comment by turboMaCk** [comment]
thx for reporting this. I'll have a look into this.

**Comment by turboMaCk** [comment]
Which version of koa.js are you using?

**Comment by turboMaCk** [comment]
I think you're probably using `2.x` versions of __koa-sslify__ with `1.x` version of koa. Please use `[1.1.0](https://github.com/turboMaCk/koa-sslify/tree/v1.1.0)` version of this package.

I'm closing this issue as my investigation suggests this is the only reason why you might be experiencing this error. If it's not the case please send more information so I can reopen this issue and investigate more.
