### ISSUE TITLE
Consider adding exports.__esModule = true

### ISSUE THREAD

**Issue by damianobarbati** [turboMaCk/koa-sslify#29]
Would you consider adding the following to enable ESM users to "es6 import" koa-sslify?

https://github.com/standard-things/esm/issues/700#issuecomment-452095814

**Comment by turboMaCk** [comment]
@damianobarbati try 4.0.1 https://github.com/turboMaCk/koa-sslify/releases/tag/4.0.1

**Comment by turboMaCk** [comment]
@damianobarbati There was a major regression in 4.0.1 (I think it must have been present even in 4.0.0). Please use 4.0.2
