### ISSUE TITLE
trustProtoHeader

### ISSUE THREAD

**Issue by piotr-s-brainhub** [turboMaCk/koa-sslify#34]
In `koa-sslify@2.1.2` there was this:
```
app.use(sslify({ trustProtoHeader: true }));
```

How can I obtain the same behavior in `koa-sslify@4`?

**Comment by turboMaCk** [comment]
hi @piotr-s-brainhub check the [documentation](https://github.com/turboMaCk/koa-sslify#resolvers). Given the increasing number of different detections, this is now decoupled.

this is what you're looking for.
```
// import middleware and resolver
const {
  default: sslify, // middleware factory
  resolver: xForwardedProtoResolver // resolver needed
} = require('koa-sslify');
const Koa = require('koa');
// init middleware with resolver

app.use(sslify({ resolver }));
```

**Comment by turboMaCk** [comment]
feel free to reopen issue if you have some follow up questions

**Comment by nltesown** [comment]
There seems to be an error here. As in the docs, the line:

```js
resolver: xForwardedProtoResolver // resolver needed
```

should be:

```js
xForwardedProtoResolver: resolver // resolver needed
```

**Comment by turboMaCk** [comment]
good catch @nitesown. Do you want to open PR? I would merge it right away.
