### ISSUE TITLE
Do not append :443 [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [turboMaCk/koa-sslify#35]
I often come up with the following when deveoping/deploying my webapps:
```
app.use(sslify({ port: process.env.HTTPS }));
```

The HTTPS port is typically: 
- for development 8443 (non 443 production port)
- for production 443

This means having a redirect in production like:
```
curl mydomain.com
Redirecting to <a href="https://mydomain.com:443/">https://mydomain.com:443/</a>.
```

1) Would it be possible to prevent the :443 append when using the `https` schema (since browser implicitly adds :443)?

2) Would it be possible to prevent the trailing slash append?

BTW great work!

**Comment by turboMaCk** [comment]
Hi @damianobarbati, thanks for the issue.

May I ask what version of the package are you using? This is what `skipDefaultPort ` is good for ([docs](https://github.com/turboMaCk/koa-sslify#usage))

This option should be true by default though so the behaviour you're looking for should be for free.

In some earlier version it was not the case though so it's possible that you will need to be able to update the version of koa-sslify to get that. If you're on some recent version that this should be considered as a bug witch needs to be investigated and patched.

**Comment by damianobarbati** [comment]
@turboMaCk bumped and it works fine, thanks and sorry for the noise 🤦🏻‍♂️

The trailing slash is something preventable somehow? 
I'm enforcing no trailing slashes in our web apps and it causes a double redirect (domain.com => https://domain.com/ => https://domain.com).

**Comment by turboMaCk** [comment]
that is currently unsupported. but I'll think about it. I also hate multiple redirects and since this by definition has to do some...

Maybe try to use explicit `hostname`. That might help.
