### ISSUE TITLE
README Error

### ISSUE THREAD

**Issue by Yu-Rain** [turboMaCk/koa-sslify#36]
![屏幕快照 2019-03-11 14 24 35](https://user-images.githubusercontent.com/30950240/54104174-d296bf80-4409-11e9-9128-8aadf8fc492a.png)

**Comment by turboMaCk** [comment]
thanks, @Yu-Rain do you want to open PR to fix README?

**Comment by turboMaCk** [comment]
ping @Yu-Rain . I can easily do it myself but at the same time, you've already done most of the work by identifying the issue. Let me know if you need any assistance or anything. If you don't have time I can copy paste the correction myself to the README.

**Comment by Yu-Rain** [comment]
First of all, I want to say sorry for not replying for such a long time, because I just saw the email. 
Second, I would love to open the PR modify README. 
But I don't have a laptop right now, so I can't change the README until next Monday

**Comment by turboMaCk** [comment]
@Yu-Rain that's fine I think it can wait. thank you:)

**Comment by turboMaCk** [comment]
resolved by https://github.com/turboMaCk/koa-sslify/pull/37

**Comment by Yu-Rain** [comment]
@turboMaCk
I see that you have modified the README.
If you need any other help in the future, please feel free to contact me.

**Comment by turboMaCk** [comment]
@Yu-Rain not me, someone else submitted PR over a weekend. see what I wrote above and in #37
