### ISSUE TITLE
In addition to a 'string', support a 'function' for 'hostname' option

### ISSUE THREAD

**Issue by newhouse** [turboMaCk/koa-sslify#40]
We have a scenario where we support multiple (sub-)domains by a single app server, and when redirecting using `sslify`, we need to be a little bit smarter about choosing what - if any - alteration of the `host` we may want to do before `sslify` does its thing.

It would be nice if `options.hostname` accepted a function that was provided the `ctx` and/or `request` / `response` objects, and could decide what string to return to use as the `hostname` for each individual redirect that might take place.

Would you implement and/or take a Pull Request that adds that capability?

Thanks!

**Comment by turboMaCk** [comment]
I would consider accepting this. 

For time being this can be implemented as another middle-ware used before the koa.

**Comment by newhouse** [comment]
Yes, as a workaround I've added a middleware that may re-write the `host` header before it gets used by `sslify`. Seems to do what I want. This is what you mean, yes?

I'll see if I can't find the time to submit a PR.

**Comment by turboMaCk** [comment]
yes. I don't think it's necessarily even workaround. This library is primary meant for redirecting between protocol where things like allowed methods and the detection should be used to make certain types in middle and on site attacks harder. I think doing the redirections which are specific to sub domain routing in different middle-ware sort of makes sense. But I would be still opened to accepting PR that makes this logic more modular as long as it doesn't make API and implementation more complicated than what I feel comfortable with letting in.

**Comment by newhouse** [comment]
Exactly: I was led to seek this behavior while closing a Host Header Injection vuln during http -> https redirect. Sounds like what you're referring to? Thats is our use case, with the only weird thing being that we want to support `app.bar.com` OR `foo.bar.com` hosts, BUT anything that doesn't match those should use `app.bar.com` when redirecting.

Feels reasonable to support this use case to me?

**Comment by turboMaCk** [comment]
yeah seems reasonable. I think maybe what we can do is to have a function that would take the domain from request and either:

a) return new string (host to redirect to)
b) return undefined/null to indicate no redirect should happen

this could even replace the host setting we have now. The current major version has been out for quite a while so I feel it might be ok to break the API and make new major version.
