### ISSUE TITLE
Help/Suggestion - Enforce only if SSL available?

### ISSUE THREAD

**Issue by medoix** [turboMaCk/koa-sslify#6]
Is it possible to only enforce SSL if the server is actually listening using SSL? i.e in dev mode i don't have an SSL cert setup but in prod i do however this forces https:// no matter what and therefore fails.

**Comment by turboMaCk** [comment]
Hi! For some reason I overlooked this issue. Did you figure it out or do you need any help with this?

**Comment by medoix** [comment]
no i was not able to solve this, do you have any ideas on how to do what im asking?

**Comment by turboMaCk** [comment]
The simpler solution is to use ENV. This is what we are using in our app in company I'm working for. For example:

```js
const isProduction = process.env.NODE_ENV === 'production';

/*==============
 * ENFORCE HTTPS
===============*/
if (isProduction) {
  app.use(enforceHttps({
    trustProtoHeader: true
  }));
}
```
http://stackoverflow.com/questions/4870328/how-to-read-environment-variable-in-node-js

**Comment by medoix** [comment]
I know you don't need to answer this as it is more than likely related to koa-server but i cannot do what you suggested above with the following... if you have any ideas it would be greatly appreciated.

```
server
  .use(cors({ origin: "*" }))
  // Force HTTPS on all page
  .use(enforceHttps())
  .use(accountsRouter.routes())
  .use(accountsRouter.allowedMethods())
  .use(devicesRouter.routes())
  .use(devicesRouter.allowedMethods())
  .use(staticMiddleware)
  .use(letsencryptAcmeRouter.routes())
  .use(letsencryptAcmeRouter.allowedMethods())
  ;

module.exports = server;
```

**Comment by turboMaCk** [comment]
No problem.
As you can see this is just imperative chain of methods. Try this

```js
server
  .use(cors({ origin: "*" }))

 // Force HTTPS in production ENV
if (process.env.NODE_ENV === 'production') {
  server.use(enforceHttps())
}

server
  .use(accountsRouter.routes())
  .use(accountsRouter.allowedMethods())
  .use(devicesRouter.routes())
  .use(devicesRouter.allowedMethods())
  .use(staticMiddleware)
  .use(letsencryptAcmeRouter.routes())
  .use(letsencryptAcmeRouter.allowedMethods())
  ;

module.exports = server;
```

then when run `node app.js` htts win not be enforced but when you run `NODE_ENV=production node app.js` it will be

**Comment by medoix** [comment]
Thank you very much @turboMaCk, greatly appreciated.
